/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.controllers.AppExceptionHandler;
import com.revature.controllers.PersonController;
import com.revature.daos.PersonDao;
import com.revature.daos.PersonDaoImpl;
import com.revature.models.Person;
import com.revature.models.Type;
import com.revature.services.PersonService;
import io.javalin.Javalin;
import io.javalin.http.Context;

import java.util.List;

public class SchoolManagementDriver {

    public static void main(String[] args)  {
        JavalinApp app = new JavalinApp();
        app.start(8080);


        /*
        Javalin app = Javalin.create().start();

        PersonController personController = new PersonController();
        AppExceptionHandler appExceptionHandler = new AppExceptionHandler();

        app.get("/people", personController::handleGetAll);

        // GET /people/5
        app.get("/people/{id}", personController::handleGetOne);

        app.put("/people/{id}", personController::handleUpdate);

        app.exception(NumberFormatException.class, appExceptionHandler::handleNumberFormatException);

        app.post("/people", personController::handleCreate);

        app.delete("/people", personController::handleDelete);
         */

    }
}
